In [1]:
# 1.Create a NumPy array representing the number of likes on 7 Instagram posts and print its ndim, shape, size, dtype, itemsize, and nbytes properties.

import numpy as np

likes = np.array([120, 250, 180, 400, 320, 150, 500])

print("Array:", likes)
print("ndim:", likes.ndim)
print("shape:", likes.shape)
print("size:", likes.size)
print("dtype:", likes.dtype)
print("itemsize:", likes.itemsize)
print("nbytes:", likes.nbytes)

Array: [120 250 180 400 320 150 500]
ndim: 1
shape: (7,)
size: 7
dtype: int64
itemsize: 8
nbytes: 56


In [ ]:
# 2.Given a 2D NumPy array of daily step counts for 5 days (each row is a day, columns are morning and evening), use reshape() to convert it into a 1D array, then back to a 2D array with 5 rows and 2 columns.<br><br><em><strong>Hint:</strong> Use the shape attribute to check your array after each reshape.</em>

import numpy as np

steps = np.array([
    [3000, 5000],
    [2500, 4500],
    [4000, 6000],
    [3500, 5500],
    [2000, 4000]
])

print("Original shape:", steps.shape)

steps_1d = steps.reshape(10)
print("1D Array:", steps_1d)
print("1D Shape:", steps_1d.shape)

steps_2d = steps_1d.reshape(5, 2)
print("2D Array:\n", steps_2d)
print("2D Shape:", steps_2d.shape)

Original shape: (5, 2)
1D Array: [3000 5000 2500 4500 4000 6000 3500 5500 2000 4000]
1D Shape: (10,)
2D Array:
 [[3000 5000]
 [2500 4500]
 [4000 6000]
 [3500 5500]
 [2000 4000]]
2D Shape: (5, 2)


In [ ]:
# 3.Build a NumPy array representing the prices of 12 food items from a Zomato order, then use ravel(), flatten(), and resize() to create different shaped versions of the data and print each result.<br><br><em><strong>Constraint:</strong> Show the difference between ravel() and flatten() in your code comments.</em>

import numpy as np

prices = np.array([
    120, 250, 180, 300,
    150, 220, 90, 350,
    200, 130, 275, 160
])

food_prices = prices.reshape(3, 4)

print("Original 2D Array:")
print(food_prices)
print("Shape:", food_prices.shape)

ravel_prices = food_prices.ravel()

print("\nUsing ravel():")
print(ravel_prices)
print("Shape:", ravel_prices.shape)

flatten_prices = food_prices.flatten()

print("\nUsing flatten():")
print(flatten_prices)
print("Shape:", flatten_prices.shape)

food_prices.resize(4, 3)

print("\nUsing resize():")
print(food_prices)
print("Shape:", food_prices.shape)

Original 2D Array:
[[120 250 180 300]
 [150 220  90 350]
 [200 130 275 160]]
Shape: (3, 4)

Using ravel():
[120 250 180 300 150 220  90 350 200 130 275 160]
Shape: (12,)

Using flatten():
[120 250 180 300 150 220  90 350 200 130 275 160]
Shape: (12,)

Using resize():
[[120 250 180]
 [300 150 220]
 [ 90 350 200]
 [130 275 160]]
Shape: (4, 3)


In [ ]:
# 4.Take a 3x3 NumPy array representing a mini Spotify playlist grid (rows: playlists, columns: song counts in categories like Pop, Rock, Indie). Use both T and np.transpose() to swap rows and columns, then print the transposed array.

import numpy as np

playlist = np.array([
    [10, 5, 8], 
    [7, 12, 6],   
    [9, 4, 15]   
])

print("Original Array:")
print(playlist)

transposed_T = playlist.T
print("\nUsing T:")
print(transposed_T)

transposed_np = np.transpose(playlist)
print("\nUsing np.transpose():")
print(transposed_np)

Original Array:
[[10  5  8]
 [ 7 12  6]
 [ 9  4 15]]

Using T:
[[10  7  9]
 [ 5 12  4]
 [ 8  6 15]]

Using np.transpose():
[[10  7  9]
 [ 5 12  4]
 [ 8  6 15]]


In [ ]:
# 5.Given a 1D NumPy array of 15 Flipkart product ratings, use reshape() to convert it into a 3x5 array, then use flatten() to return it to a 1D array. Explain in a comment when you would use flatten() versus ravel() in real projects.

import numpy as np

ratings = np.array([
    5, 4, 3, 5, 4,
    2, 5, 3, 4, 5,
    4, 3, 5, 2, 4
])

ratings_2d = ratings.reshape(3, 5)

print("3x5 Array:")
print(ratings_2d)
print("Shape:", ratings_2d.shape)

ratings_1d = ratings_2d.flatten()

print("\n1D Array:")
print(ratings_1d)
print("Shape:", ratings_1d.shape)


3x5 Array:
[[5 4 3 5 4]
 [2 5 3 4 5]
 [4 3 5 2 4]]
Shape: (3, 5)

1D Array:
[5 4 3 5 4 2 5 3 4 5 4 3 5 2 4]
Shape: (15,)
