In [1]:
# 1.Create two NumPy arrays representing the ratings of 5 restaurants on Zomato and Swiggy, then use np.concatenate() to combine them into a single array of 10 ratings and print the result.

import numpy as np

zomato = np.array([4.2, 4.5, 3.8, 4.7, 4.0])
swiggy = np.array([4.1, 4.3, 3.9, 4.6, 4.4])

combined = np.concatenate((zomato, swiggy))

print("Combined Ratings:", combined)

Combined Ratings: [4.2 4.5 3.8 4.7 4.  4.1 4.3 3.9 4.6 4.4]


In [2]:
# 2.Given three arrays representing the number of likes on three different Instagram posts over 7 days, stack them vertically using np.vstack() so that each row represents one post's weekly likes, and print the stacked array.

import numpy as np

post1 = np.array([120, 150, 180, 200, 220, 250, 300])
post2 = np.array([100, 140, 160, 190, 210, 230, 280])
post3 = np.array([130, 170, 200, 220, 240, 270, 320])

stacked = np.vstack((post1, post2, post3))

print("Stacked Array:")
print(stacked)

Stacked Array:
[[120 150 180 200 220 250 300]
 [100 140 160 190 210 230 280]
 [130 170 200 220 240 270 320]]


In [3]:
# 3.You have an array of 12 Flipkart product IDs. Use np.array_split() to divide this array into 5 nearly equal parts, and display each part.<br><br><em><strong>Hint:</strong> Check the shape of each split to confirm the division.</em>

import numpy as np

product_ids = np.array([
    101, 102, 103, 104,
    105, 106, 107, 108,
    109, 110, 111, 112
])

parts = np.array_split(product_ids, 5)

for i, part in enumerate(parts, 1):
    print("Part", i, ":", part)
    print("Shape:", part.shape)

Part 1 : [101 102 103]
Shape: (3,)
Part 2 : [104 105 106]
Shape: (3,)
Part 3 : [107 108]
Shape: (2,)
Part 4 : [109 110]
Shape: (2,)
Part 5 : [111 112]
Shape: (2,)


In [ ]:
# 4.Simulate a WhatsApp group chat: create a 2D NumPy array where each row is a user and each column is the number of messages sent per day for a week. Use np.insert() to add a new user (row) with their message counts, then use np.delete() to remove the user who sent the least messages overall.

import numpy as np

chat = np.array([
    [10, 15, 12, 20, 18, 14, 16],
    [25, 20, 30, 22, 28, 24, 26],
    [5,  8,  6,  7,  9,  4,  6]
])

new_user = np.array([12, 10, 15, 18, 14, 16, 20])

chat = np.insert(chat, 3, new_user, axis=0)

print("After adding new user:")
print(chat)

totals = np.sum(chat, axis=1)
least_user = np.argmin(totals)

chat = np.delete(chat, least_user, axis=0)

print("\nAfter removing least active user:")
print(chat)

After adding new user:
[[10 15 12 20 18 14 16]
 [25 20 30 22 28 24 26]
 [ 5  8  6  7  9  4  6]
 [12 10 15 18 14 16 20]]

After removing least active user:
[[10 15 12 20 18 14 16]
 [25 20 30 22 28 24 26]
 [12 10 15 18 14 16 20]]


In [ ]:
# 5.Given a NumPy array of YouTube video view counts, use .view() to create a view and .copy() to create a copy. Modify the first element in each and print all arrays to demonstrate the difference between view and copy.<br><br><em><strong>Hint:</strong> Observe which changes affect the original array.</em>

import numpy as np

views = np.array([1000, 2500, 5000, 7500, 10000])

view_array = views.view()
copy_array = views.copy()

view_array[0] = 9999
copy_array[0] = 8888

print("Original Array:", views)
print("View Array:", view_array)
print("Copy Array:", copy_array)

Original Array: [ 9999  2500  5000  7500 10000]
View Array: [ 9999  2500  5000  7500 10000]
Copy Array: [ 8888  2500  5000  7500 10000]
