In [ ]:
# 1.Create a NumPy array called prices with the following values: [199, 299, 399, 499, 599]. Use basic indexing to print the first and last price.

import numpy as np

prices = np.array([199, 299, 399, 499, 599])

print("First price:", prices[0])
print("Last price:", prices[-1])

First price: 199
Last price: 599


In [ ]:
# 2.Given a 2D NumPy array representing cricket scores for 3 players across 5 matches, use slicing to extract the scores of all players for matches 2 to 4 (index 1 to 3).

import numpy as np

scores = np.array([
    [45, 60, 72, 55, 80],
    [50, 65, 70, 62, 75],
    [40, 58, 68, 50, 85]
])

result = scores[:, 1:4]

print(result)

[[60 72 55]
 [65 70 62]
 [58 68 50]]


In [ ]:
# 3.You have a NumPy array called ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5]). Use negative indexing to print the last three ratings.

import numpy as np

ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])

print(ratings[-3:])

[2.9 5.  3.5]


In [ ]:
# 4.Create a NumPy array of the first 20 natural numbers. Use step slicing to print every 3rd number starting from the second element.<br><br><em><strong>Hint:</strong> Use the slice notation with a step value.</em>

import numpy as np

numbers = np.arange(1, 21)

result = numbers[1::3]

print(result)

[ 2  5  8 11 14 17 20]


In [5]:
# 5.Given a NumPy array of Flipkart product prices, use boolean indexing to extract all prices greater than 500. Print the resulting array.

import numpy as np

prices = np.array([250, 650, 450, 800, 1200, 350, 550, 300])

result = prices[prices > 500]

print(result)

[ 650  800 1200  550]


In [ ]:
# 6.You have an array of IPL team scores: np.array([210, 180, 195, 220, 205, 175]). Use np.where() to find the indices of all scores above 200 and print these indices.

import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])

indices = np.where(scores > 200)

print("Indices:", indices[0])

Indices: [0 3 4]
